<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>Chandam</RootNamespace>
    <AssemblyName>Chandam</AssemblyName>
    <ApplicationIcon>Miriyam.ico</ApplicationIcon>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
    <GenerateAssemblyInformationalVersionAttribute>false</GenerateAssemblyInformationalVersionAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
    <GenerateAssemblyVersionAttribute>false</GenerateAssemblyVersionAttribute>
    <NoWarn>CS8981</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Extractor.cs" />
    <Compile Include="Program.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="StopWatch.cs" />
    <Compile Include="StyleSheet.cs" />
    <Compile Include="Worker.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Miriyam.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Chandam.Core.csproj" />
    <ProjectReference Include="..\Rules\Chandam.Rules.csproj" />
    <ProjectReference Include="..\Strings\Chandam.Indic.csproj" />
    <ProjectReference Include="..\Util\Chandam.Util.csproj" />
  </ItemGroup>
</Project>
