<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Core</RootNamespace>
    <AssemblyName>Chandam.Core</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Chandam\CheatSheet.cs" />
    <Compile Remove="Chandam\CheatSheet2.cs" />
    <Compile Remove="Chandam\Helper2.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Chandam.Rules\Chandam.Rules.csproj" />
    <ProjectReference Include="..\Chandam.Samples\Chandam.Samples.csproj" />
    <ProjectReference Include="..\Chandam.Indic\Chandam.Indic.csproj" />
    <ProjectReference Include="..\Chandam.Util\Chandam.Util.csproj" />
  </ItemGroup>

</Project>
