<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Core</RootNamespace>
    <AssemblyName>Chandam.Core</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
    <GenerateAssemblyInformationalVersionAttribute>false</GenerateAssemblyInformationalVersionAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
    <GenerateAssemblyVersionAttribute>false</GenerateAssemblyVersionAttribute>
    <NoWarn>CS8981</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Business\Business.cs" />
    <Compile Include="Business\Business2.cs" />
    <Compile Include="Business\Business3.cs" />
    <Compile Include="Context.cs" />
    <Compile Include="Samples\Format.cs" />
    <Compile Include="Samples\Poem.cs" />
    <Compile Include="Chandam\MatchOptions.cs" />
    <Compile Include="Samples\Satakam.cs" />
    <Compile Include="Samples\Satakam2.cs" />
    <Compile Include="Samples\SatakamData.cs" />
    <Compile Include="Unclassified\SortHelper2.cs" />
    <Compile Include="Reports\ChandamReports.cs" />
    <Compile Include="Chandam\Prasa.cs" />
    <Compile Include="Chandam\Yati.cs" />
    <Compile Include="Chandam\YatiChecker2.cs" />
    <Compile Include="Chandam\Errors.cs" />
    <Compile Include="Chandam\MatchResult.cs" />
    <Compile Include="Chandam\Padyam.cs" />
    <Compile Include="Chandam\Probable.cs" />
    <Compile Include="Chandam\Ranges.cs" />
    <Compile Include="Chandam\YatiChecker3.cs" />
    <Compile Include="Labs\Machine.cs" />
    <Compile Include="Reports\YatiPrasaTester.cs" />
    <Compile Include="Chandam\IndexBuilder.cs" />
    <Compile Include="Chandam\GSplitter.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="Tests\SanityTest.cs" />
    <Compile Include="Unclassified\Strings.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rules\Chandam.Rules.csproj" />
    <ProjectReference Include="..\Samples\Chandam.Samples.csproj" />
    <ProjectReference Include="..\Strings\Chandam.Indic.csproj" />
    <ProjectReference Include="..\Util\Chandam.Util.csproj" />
  </ItemGroup>
</Project>
