<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Indic</RootNamespace>
    <AssemblyName>Chandam.Indic</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
    <GenerateAssemblyInformationalVersionAttribute>false</GenerateAssemblyInformationalVersionAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
    <GenerateAssemblyVersionAttribute>false</GenerateAssemblyVersionAttribute>
    <NoWarn>CS8981</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="DevaNagariBase\DevaNagariCharSet.cs" />
    <Compile Include="DevaNagariBase\DevanagariAksharam.cs" />
    <Compile Include="iIndicCharSet.cs" />
    <Compile Include="IndicAkshar.cs" />
    <Compile Include="IndicChar.cs" />
    <Compile Include="IndicParser.cs" />
    <Compile Include="KannadaBase\KannadaAksharam.cs" />
    <Compile Include="KannadaBase\KannadaCharSet.cs" />
    <Compile Include="Partial.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="SimpleInidicParser.cs" />
    <Compile Include="IndicAkshar2.cs" />
    <Compile Include="TeluguBase\TeluguAksharam.cs" />
    <Compile Include="TeluguBase\TeluguCharSet.cs" />
    <Compile Include="TeluguBase\TeluguParaser.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Util\Chandam.Util.csproj" />
  </ItemGroup>
</Project>
