<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Samples</RootNamespace>
    <AssemblyName>Chandam.Samples</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
    <GenerateAssemblyInformationalVersionAttribute>false</GenerateAssemblyInformationalVersionAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
    <GenerateAssemblyVersionAttribute>false</GenerateAssemblyVersionAttribute>
    <NoWarn>CS8981</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="Bhaskara.cs" />
    <Compile Include="Kumara.cs" />
    <Compile Include="MyFavPoems.cs" />
    <Compile Include="SriKalaHadteeswara.cs" />
    <Compile Include="SriRama.cs" />
    <Compile Include="Sumati.cs" />
    <Compile Include="Vemana.cs" />
    <Compile Include="_iSamplePoems.cs" />
    <Compile Include="_None.cs" />
  </ItemGroup>
</Project>
