<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(ExcludeYaml)' == 'true'">
    <DefineConstants>$(DefineConstants);EXCLUDE_YAML</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Chandam.Core\Chandam.Core.csproj" />
    <ProjectReference Include="..\Chandam.Rules\Chandam.Rules.csproj" />
    <ProjectReference Include="..\Chandam.Util\Chandam.Util.csproj" />
    <ProjectReference Include="..\Chandam.Indic\Chandam.Indic.csproj" />
    <ProjectReference Include="..\Chandam.Samples\Chandam.Samples.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="9.0.1" />
    <PackageReference Include="YamlDotNet" Version="16.2.1" Condition="'$(ExcludeYaml)' != 'true'" />
  </ItemGroup>

</Project>
