<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Rules</RootNamespace>
    <AssemblyName>Chandam.Rules</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Sans\X.cs" />
    <Compile Remove="StringUtil.cs" />
    <Compile Remove="StringUtil2.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Util\Chandam.Util.csproj" />
  </ItemGroup>

</Project>
